# Generated by Django 3.2.4 on 2021-09-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='qty',
        ),
    ]
